-- MySQL Script generated by MySQL Workbench
-- Sun Feb  6 18:57:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema productsdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema productsdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productsdatabase` DEFAULT CHARACTER SET utf8 ;
USE `productsdatabase` ;

-- -----------------------------------------------------
-- Table `productsdatabase`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productsdatabase`.`table1` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `skuValue` VARCHAR(45) NULL,
  `nameValue` VARCHAR(45) NULL,
  `priceValue` VARCHAR(45) NULL,
  `dvdSizeValue` VARCHAR(45) NULL,
  `bookWeightValue` VARCHAR(45) NULL,
  `furnitureHeightValue` VARCHAR(45) NULL,
  `furnitureWidthValue` VARCHAR(45) NULL,
  `furnitureLengthValue` VARCHAR(45) NULL,
  PRIMARY KEY (`productId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
